### ISSUE TITLE
Cannot nest checkouts of git repositories

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/manage_externals#104]

**Comment by billsacks** [comment]
What version of git causes the problem? Note that versions prior to 1.8 (or maybe something late in the 1.7 series like 1.7.10) have trouble even cloning from github directly - this is a github issue, not a manage_externals issue per se. That said, I don't mind having this check in manage_externals for convenience.

**Comment by jedwards4b** [comment]
It was the default git version on cheyenne - the problem is that it took a good hour to figure out that this was a git problem and not a manage_externals problem - checking for the minimum git version should reduce the problems reported.

**Comment by jedwards4b** [comment]
git version 1.8.5.6 did not work
git version 2.10.2 did

**Comment by billsacks** [comment]
What was the exact problem? I know that Ben and/or I tested with version 1.8.x in the past and it worked, so I'm wondering if a recent change broke it.

**Comment by jedwards4b** [comment]
It turns out that it isn't working in git 2.10.2 either but it's failing in a different way.   Lets look at it together tomorrow.

**Comment by jedwards4b** [comment]
The issue is that 
git clone -bjedwards/mom6_update https://github.com/ESCOMP/UFSCOMP.git
Does not get the z_da_hooks external defined in components/mom/Externals_MOM.cfg

**Comment by billsacks** [comment]
I played around with this a bit just now. I see that the end result of doing a clone followed by checkout_externals is really messed up within MOM6. My first thought is that this is arising from trying to check out a git repo under another git repo. I think that, for this to work right, .gitignore in MOM6 needs to ignore the path pkg/MOM6_DA_hooks.

However, I'm still not sure this would be guaranteed to work as it's currently set up: If manage_externals first gets this:

```cfg
[z_da_hooks]
branch = master
protocol = git
local_path = MOM6/pkg/MOM6_DA_hooks
repo_url = https://github.com/MJHarrison-GFDL/MOM6_DA_hooks.git
required = True
```

and second gets this:

```cfg
[mom]
branch = dev/ncar
protocol = git
local_path = MOM6
repo_url = https://github.com/NCAR/MOM6.git
required = True
```

It seems like weird things could happen: i.e., it's first populating MOM6/pkg/MOM6_DA_hooks with a git repo, then second turning MOM6 into its own git repo... what would happen to the subdirectory under this? Maybe putting mom before z_da_hooks would solve this, but I'm not sure if manage_externals guarantees that a cfg file is parsed in order. Another solution would be to make z_da_hooks a sub-external of MOM6 - so the above Externals file would only get MOM6, and then MOM6 would get z_da_hooks, guaranteeing that z_da_hooks is retrieved after its parent directory. (Even in this case, though, it's still important to add the directory to gitignore.)

**Comment by billsacks** [comment]
I'm changing the title to reflect the true issue.

**Comment by jedwards4b** [comment]
One of the goals is to change nothing in the MOM6 directory.   I have updated the UFSCOMP with a solution.

**Comment by billsacks** [comment]
So should we close this issue, or is there still something you'd like to address in manage_externals?

**Comment by jedwards4b** [comment]
I think that its an open issue - I think we should be able to emulate git submodules.

**Comment by jedwards4b** [comment]
The actual issue is that the subdirectory I am asking to clone into already exists in the repo.   I think I can modify manage_externals to do the right thing if a clone directory exists but is empty.
