### ISSUE TITLE
Cannot switch to an svn tag that doesn't share ancestry

### ISSUE THREAD

**Issue by billsacks** [ESMCI/manage_externals#105]
When trying to switch to an svn tag that doesn't share ancestry with the currently-checked-out tag, an error results:

```
s   ./components/cam
        clean sandbox, cam1/trunk_tags/cam5_4_182/components/cam --> cam1/branch_tags/cam_cesm2_0_rel_tags/cam_cesm2_0_rel_02
    svn switch --quiet https://svn-ccsm-models.cgd.ucar.edu/cam1/branch_tags/cam_cesm2_0_rel_tags/cam_cesm2_0_rel_02
ERROR:root:Command '[u'svn', u'switch', u'--quiet', u'https://svn-ccsm-models.cgd.ucar.edu/cam1/branch_tags/cam_cesm2_0_rel_tags/cam_cesm2_0_rel_02']' returned non-zero exit status 1
ERROR:root:Failed with output:
    svn: E195012: Path '.' does not share common version control ancestry with the requested switch location.  Use --ignore-ancestry to disable this check.
    svn: E195012: 'https://svn-ccsm-models.cgd.ucar.edu/cam1/branch_tags/cam_cesm2_0_rel_tags/cam_cesm2_0_rel_02' shares no common ancestry with '/Users/sacks/cesm_code/cesm/components/cam'

ERROR: In directory
    /Users/sacks/cesm_code/cesm/components/cam
Process did not run successfully; returned status 1:
    svn switch --quiet https://svn-ccsm-models.cgd.ucar.edu/cam1/branch_tags/cam_cesm2_0_rel_tags/cam_cesm2_0_rel_02
See above for output from failed command.
Please check the log file manage_externals.log for more details.

ERROR: Failed with output:
    svn: E195012: Path '.' does not share common version control ancestry with the requested switch location.  Use --ignore-ancestry to disable this check.
    svn: E195012: 'https://svn-ccsm-models.cgd.ucar.edu/cam1/branch_tags/cam_cesm2_0_rel_tags/cam_cesm2_0_rel_02' shares no common ancestry with '/Users/sacks/cesm_code/cesm/components/cam'

ERROR: In directory
    /Users/sacks/cesm_code/cesm/components/cam
Process did not run successfully; returned status 1:
    svn switch --quiet https://svn-ccsm-models.cgd.ucar.edu/cam1/branch_tags/cam_cesm2_0_rel_tags/cam_cesm2_0_rel_02
See above for output from failed command.
Please check the log file manage_externals.log for more details.
```

**Comment by billsacks** [comment]
@jedwards4b - I'll fix this by adding `--ignore-ancestry` in the svn switch command, unless you can see any issues with doing so.

**Comment by billsacks** [comment]
Never mind - I misdiagnosed the problem: it turns out the real issue was that the cam external was listed incorrectly in Externals.cfg on cesm master. So this was picking up a true problem, and I don't think we should add `--ignore-ancestry` after all.

**Comment by billsacks** [comment]
Reopening because it seems like this is a continued problem - https://github.com/ESCOMP/cesm/issues/64 . @jedwards4b do you think we should add `--ignore-ancestry` to the `svn switch` command?

**Comment by billsacks** [comment]
@jedwards4b I won't make you repeat your comment from https://github.com/ESCOMP/cesm/issues/64#issuecomment-399587374 . I'll close this as a wontfix. If we find users are running into this frequently, we can reconsider, or consider somehow trying to catch this error and writing out a helpful message.

**Comment by mnlevy1981** [comment]
Re-opening this discussion because both @matt-long and I have been tripped up by this when dealing updating along the CESM 2.1 release / release candidate tags and I think it's worth revisiting.

I don't think it's a good idea to add `--ignore-ancestry` to every `svn switch` call, but what if `checkout_externals` had an `--ignore-ancestry` flag that could be passed through to subversion? I.e.

```
$ ./manage_externals/checkout_externals
[SVN errors from CAM and POP due to lack of common ancestry]
$ ./manage_externals/checkout_externals --ignore-ancestry
[successfully switches CAM and POP to new release tags]
```

**Comment by billsacks** [comment]
@mnlevy1981 that seems like a good compromise, though I'd suggest `--svn-ignore-ancestry`. One hard part will be figuring out how to make it clear to users that they should try using this flag in this particular situation. (Unless you imagine this being something added for those in the know, without an attempt made to document it thoroughly... which might be okay.)

**Comment by mnlevy1981** [comment]
`--svn-ignore-ancestry` makes sense. I think documenting it through `argparse` with a description along the lines of `use the --ignore-ancestry flag when calling svn switch` would be sufficient - in my mind it's an "expert only" feature so it doesn't require much in the way of documentation.

**Comment by billsacks** [comment]
@mnlevy1981 Do you want to take a stab at implementing this?

**Comment by matt-long** [comment]
I would suggest that if this takes more than an hour or so to implement, we should just wait for the components to move to git and live with the annoyance.

**Comment by mnlevy1981** [comment]
@billsacks I think this would take 15 or 20 minutes if I were sitting down with someone who is already familiar with the `checkout_externals` calling tree, but far longer if I were to try to tackle it alone. Maybe we could sit down together sometime this week? If not, I'm okay with @matt-long's plan of re-labeling this `wontfix` and waiting for the move to git.
