### ISSUE TITLE
Add some more details about when you need to rerun checkout_externals

### ISSUE THREAD

**Issue by billsacks** [ESMCI/manage_externals#12]
I feel we should add some more details about when you need to rerun checkout_externals. Something like:

You need to rerun checkout_externals.py whenever CESM.xml has changed (unless you have already manually updated the relevant external(s) to have the correct branch/tag checked out). Common times when this is needed are:
- After checking out a new branch/tag
- After merging some other branch/tag into your currently checked-out branch

**Comment by bandre-ucar** [comment]
I updated the doc a bit to specify 'when externals file has changed'. But I think *why* it changed is a workflow discussion that is better documented in context it the cesm and clm workflows. Bill and Mariana have a nice start on this at: 

https://github.com/ESCOMP/cesm/pull/2
