### ISSUE TITLE
Support for Git sparse checkout

### ISSUE THREAD

**Issue by tclune** [ESMCI/manage_externals#120]
### Summary of Issue:   

Provide option to have git suppress some directories in the work tree.  E.g. our CTM app must include our entire GCM to obtain the advection core.  (Chemistry will be in a separate repo).   By using git "sparse checkout" capabilities, CTM users will not see most of the rest of the GCM - just the core directory.

In theory this could be avoided by adopting an even more fine-grained repository decomposition, but we are not prepared to go as far as would be required.  Virtually all changes would then span multiple repositories which is undesirable.

### Expected behavior and actual behavior:  

Config file would have an optional entry for each repo which specifies a "sparse" config file that would be used to exercise native git capabilities  to suppress directories.   This would be applied _after_ switching branches.

Example providing this option
```config
[GEOSgcm_GridComp]
required = True
repo_url = git@developer.nasa.gov:GEOSproto/GEOSgcm.git
local_path = ./src/Components/GEOSgcm_GridComp
branch = master
protocol = git
externals = Externals.cfg
sparse-checkout = my_sparse
```
Example sequence of extra commands that would be issued during the configuration:

```shell
git config core.sparsecheckout true
cp <sparse-checkout> $GITDIR/info/sparse-checkout
git read-tree -mu HEAD
```
It really is just a matter of tacking these 3 commands to the end of the git checkout sequence, which is why I'm confident this is an easy change without even looking at the python source.   I'm not wed to the particular name for the option.   "sparse-checkout" is the internal file name that Git  

### What is the changeset ID of the code, and the machine you are using:

N/A

### have you modified the code? If so, it must be committed and available for testing:

N/A

### Screen output or log file showing the error message and context:

N/A

**Comment by gold2718** [comment]
One comment: Instead of `sparse-checkout`, please use an underscore, `sparse_checkout`.

**Comment by gold2718** [comment]
Why use `read-tree` instead of just using `checkout` once the config is set? Maybe something like:
```
git clone --no-checkout $URL
git config core.sparsecheckout true
cp <my_sparse> $GITDIR/info/sparse-checkout
git checkout <hash|tag>
```
