### ISSUE TITLE
deep clone of sandbox?

### ISSUE THREAD

**Issue by tclune** [ESMCI/manage_externals#130]
### Summary of Issue:
Is there a simple way to make a deep clone of a sandbox derived with manage-externals?      This is in the case where there are subsequent locally committed changes.    The complexity of sharing code with others when multiple repositories must coordinate for a given change is challenging our users on a regular basis.

My thought was that it should be straightforward to navigate the nested externals file in the source sandbox simply to find the mount points.  For each of those a clone is performed into the new sandbox at the corresponding mount point.

### Expected behavior and actual behavior:
N/A

### Steps to reproduce the problem (should include model description file(s) or link to publi c repository):
N/A

### What is the changeset ID of the code, and the machine you are using:
N/A
### have you modified the code? If so, it must be committed and available for testing:
N/A
### Screen output or log file showing the error message and context:
N/A

**Comment by billsacks** [comment]
There currently are no mechanisms in place to help with this, but I can see how it could be valuable to support this. This seems at least slightly related to #14 , but my understanding is that you want an ability to copy whatever is currently committed locally, even if it hasn't been pushed back to the remote repository referenced in Externals.cfg (via a local clone)? (You might be able to achieve something like this via the local_path capability of manage_externals – search for `local_path`/`LOCAL_PATH` in the manage_externals repo to see what I'm referring to. But I'm not very familiar with the use of that feature, and I'm not sure how close that would get you to what you want.)

**Comment by gold2718** [comment]
@tclune,

How is the proposed functionality different from a `cp -R` or `rsync` call?
Is it to avoid uncommitted changes and untracked files? Something else?

**Comment by tclune** [comment]
Fair point - I'd not even considered the old-school approach.   

The only problem that I immediately see with a direct copy would be the expensive copy of the build/install directories which might be under the top dir as siblings of ./src.      Since we've mostly standardized that, it should be easy to skip those trees with a "smart" cp, or in the worst case suffer the extra cost of copying and manually deleting on the receiving end.

I'm going to close the issue for now, and will reopen if I (or anyone else) have new insights.
