### ISSUE TITLE
manage_externals NOT passing all of it's tests on cheyenne

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/manage_externals#141]
### Summary of Issue:

The tests for manage_externals aren't all passing when run on cheyenne.

### Expected behavior and actual behavior:

I expect all of the tests to run, but 3 fail on cheyenne having to do with "OutsideGitRepo".

Tests all PASS on my Mac laptop, and on hobart.

### What is the changeset ID of the code, and the machine you are using: both manic-v1.1.8-2-gc33a3bd, and manic-v1.1.8

It works in manic-v1.1.0, but fails in versions beyond that

### Screen output or log file showing the error message and context:

> manage_externals/test> make test
> PYTHONPATH=..: python -m unittest discover --buffer --pattern 'test_unit_*.py'
> ...................................................................................................................
> ----------------------------------------------------------------------
> Ran 115 tests in 0.037s
> 
> OK
> PYTHONPATH=..: python -m unittest discover --buffer --pattern 'test_sys_*.py'
> ..........................FF...F....
> ======================================================================
> FAIL: test_currentBranch_outsideGitRepo (test_sys_repository_git.TestGitRepositoryGitCommands)
> Ensure that the _git_current_branch function returns False
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "test_sys_repository_git.py", line 205, in test_currentBranch_outsideGitRepo
>     self.assertFalse(branch_found)
> AssertionError: True is not false
> 
> ======================================================================
> FAIL: test_currentHash_outsideGitRepo (test_sys_repository_git.TestGitRepositoryGitCommands)
> Ensure that the _git_current_hash function returns False when
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "test_sys_repository_git.py", line 177, in test_currentHash_outsideGitRepo
>     self.assertFalse(hash_found)
> AssertionError: True is not false
> 
> ======================================================================
> FAIL: test_currentTag_outsideGitRepo (test_sys_repository_git.TestGitRepositoryGitCommands)
> Ensure that the _git_current_tag function returns False when
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "test_sys_repository_git.py", line 233, in test_currentTag_outsideGitRepo
>     self.assertFalse(tag_found)
> AssertionError: True is not false
> 
> ----------------------------------------------------------------------
> Ran 36 tests in 43.020s
> 
> FAILED (failures=3)
> Makefile:64: recipe for target 'stest' failed
> make: *** [stest] Error 1

**Comment by gold2718** [comment]
Do the tests report the `git` version? The default `git` on Cheyenne is older than the version you get with `module load git`.

**Comment by ekluzek** [comment]
I don't see that the tests themselves report the git version. But, you are right I was using the older default which is:

git version 2.12.3

However, I still get the same behavior when doing using the module load that uses version 2.22.0.

**Comment by billsacks** [comment]
I think I see the problem, which is a funny one (if you're into this kind of humor):

Those tests create a test directory in your temp space. Erik, according to your .cshrc file, you have changed your tmp space on cheyenne to use `/glade/work/erik/tmp`. For some reason, it appears that your entire work directory has become a git repository based on CTSM, so your tmp directory is inside a git repo. So when this test says, "I shouldn't be inside a git repo", it fails, because this temp directory IS within a git repository.

Unless this was intentional, I suggest removing the directory `/glade/work/erik/.git`

**Comment by ekluzek** [comment]
This is definitely not intentional. And I'll take it as humorous as well. For some reason it's not allowing me to delete the .git directory, calling it a "Read-only file system". But, I'll get the system people to help me with that. I'll close this once I can show that it works.

Thanks for figuring this out, I'm impressed. Nice, to know it was just failing for me, and not anyone else.

**Comment by ekluzek** [comment]
OK, once I renamed the .git directory to gitremove, I was able to delete it normally with no problem. I'm not sure why that mattered, but it did.

But, now it's working normally and passes all the tests. So it's all good.
