### ISSUE TITLE
shebang lines need to be updated to python3

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/manage_externals#160]
### Summary of Issue:

The shebang lines in manage_externals are all python and should be updated to python3

### Screen output or log file showing the error message and context:

git grep "env python"
checkout_externals:#!/usr/bin/env python
manic/checkout.py:#!/usr/bin/env python
manic/externals_description.py:#!/usr/bin/env python
manic/utils.py:#!/usr/bin/env python
test/test_sys_checkout.py:#!/usr/bin/env python
test/test_sys_repository_git.py:#!/usr/bin/env python
test/test_unit_externals_description.py:#!/usr/bin/env python
test/test_unit_externals_status.py:#!/usr/bin/env python
test/test_unit_repository.py:#!/usr/bin/env python
test/test_unit_repository_git.py:#!/usr/bin/env python
test/test_unit_repository_svn.py:#!/usr/bin/env python
test/test_unit_utils.py:#!/usr/bin/env python

**Comment by billsacks** [comment]
@fischer-ncar can you please take this once the cime split beta tag is done?

**Comment by jedwards4b** [comment]
@fischer-ncar this still needs done.
