### ISSUE TITLE
document dependencies

### ISSUE THREAD

**Issue by bandre-ucar** [ESMCI/manage_externals#21]
### Summary of Issue:

Document manage_externals depenecies:

* git - 1.8, 2.3 <= version <= 2.15
* svn - 1.6.11 <= version <= 1.9.4
* python
  - python2 > 2.7.z
  - python3 > 3.4.z

**Comment by bandre-ucar** [comment]
bandre testing:  git 2.15, svn 1.9.4, python 2.7.10
cheyenne testing: git 2.10 svn 1.8.10, 2.7.13

**Comment by bandre-ucar** [comment]
CI testing:
* python - 2.7, 3.4, 3.5, 3.6
* git - 2.14.1

**Comment by billsacks** [comment]
Thanks for this.

Minor quibble: dependencies not dependancies

**Comment by bandre-ucar** [comment]
hobart:
$ git --version
git version 1.8.3.1

**Comment by bandre-ucar** [comment]
@bertinia I'd like to move this info and close this issue. Any suggestions for the correct location?

**Comment by bertinia** [comment]
Can @bandre-ucar add it to the checkout_externals.py -v option so it displays 
automatically on the main repo README?

**Comment by billsacks** [comment]
I have opened https://github.com/ESCOMP/cesm/pull/14 . I think the top-level CESM is a better place to document these dependencies. I'd be fine with closing this issue.

**Comment by bandre-ucar** [comment]
checkout_externals works on yellowstone with:
* svn 1.6.11
* git 2.3.0

**Comment by billsacks** [comment]
@bandre-ucar I'm fine with this issue being closed if you are.

**Comment by bandre-ucar** [comment]
Documented in cesm documentation and I've added a wiki page to manage_externals.
