### ISSUE TITLE
Add status writes to manage_externals

### ISSUE THREAD

**Issue by billsacks** [ESMCI/manage_externals#28]
_From @cacraigucar on November 20, 2017 21:2_

Going from a git or svn checkout where the screen is inundated with every file checked out, to manage_externals where it silently sits there for minutes can be disconcerting as you are not sure if the command is making progress or not.  A simple "starting to check out XXX", "completed check out of XXX" for each of the components would be useful so the user can make sure progress is actually being made. I ended up opening a new window and seeing that something was happening just to make sure progress was being made and it wasn't simply hung.

_Copied from original issue: ESCOMP/cesm#4_

**Comment by billsacks** [comment]
I'll add that I personally like the current level of verbosity: I like messages to be kept to a minimum unless something goes wrong, in order to highlight warnings / errors more clearly.

**Comment by bandre-ucar** [comment]
checkout_externals already prints the current external name as it begins working on that external. I paid a bit more attention to it when it was running, and noticed that stdout was being buffered. I'm flushing stdout more frequently, and it gives more of a 'progress' bar feel as intended (#31 ).

Not everyone likes running svn in verbose mode, and it hides errors.

I think people need to give this format a try and get use to the new output format for a while and we can revisit later.
