### ISSUE TITLE
Better error message needed when running checkout_externals.py not in root of source tree

### ISSUE THREAD

**Issue by billsacks** [ESMCI/manage_externals#29]
_From @cacraigucar on November 20, 2017 21:13_

While the help message highlights that checkout_externals.py must be run in the root of the source tree, the error message indicates a different error.  The error message is about "not being able to find the model description file".   It should probably also suggest:  "Is this command being run from the root of the source tree?"

_Copied from original issue: ESCOMP/cesm#5_

**Comment by bandre-ucar** [comment]
Updated in #41.
