### ISSUE TITLE
Improve output of checkout_externals

### ISSUE THREAD

**Issue by mnlevy1981** [ESMCI/manage_externals#43]
### Summary of Issue:

The first time I ran the program, I saw

```
$ ./manage_externals/checkout_externals
Processing externals description file : CESM.cfg
Checking status of components: clm, mosart, ww3, cime, cice, pop, cism, rtm, cam, cime_config,
Checkout components: clm,
```
And it was unclear to me that the last line was a progress update (I thought it was an input prompt)

Something like

```
Processing externals description file : CESM.cfg
Checking status of components: clm, mosart, ww3, cime, cice, pop, cism, rtm, cam, cime_config,
Checking out components:
clm...
```

Would be much clearer, although the final result would be more screen real estate:

```
Processing externals description file : CESM.cfg
Checking status of components: clm, mosart, ww3, cime, cice, pop, cism, rtm, cam, cime_config,
Checking out components:
clm... done
mosart... done
ww3... done
cime... done
cice... done
pop... done
cism... done
rtm... done
cam... done
cime_config... done
```

instead of

```
Processing externals description file : CESM.cfg
Checking status of components: clm, mosart, ww3, cime, cice, pop, cism, rtm, cam, cime_config,
Checkout components: clm, mosart, ww3, cime, cice, pop, cism, rtm, cam, cime_config,
```

For consistency, it may also be worth cleaning up `Checking status of components` but really it's just the phrase `Checkout components` makes me think I need to provide a response.

### Expected behavior and actual behavior:

see above

### Steps to reproduce the problem (should include model description file(s) or link to publi c repository):

just run `checkout_externals`

### What is the changeset ID of the code, and the machine you are using:

using `cesm2_0_beta07.002` from [ESCOMP/cesm](https://github.com/ESCOMP/cesm)

### have you modified the code? If so, it must be committed and available for testing:

nope, this was out of the box

### Screen output or log file showing the error message and context:

see above

**Comment by bandre-ucar** [comment]
Closed by GH-63
