### ISSUE TITLE
Enhancement request: more verbosity when running checkout_externals with -v

### ISSUE THREAD

**Issue by billsacks** [ESMCI/manage_externals#46]
I'm opening this enhancement request on behalf of @cecilehannay , but I see her point, too.

While I like the default behavior of checkout_externals in terms of the level of verbosity, there are times when some extra verbosity can be reassuring, especially when you have changed the CESM.cfg file and are rerunning checkout_externals, and want to see that it's actually doing something.

Our thought is that, when you add the `-v` flag, you should see all of the output from the underlying `git checkout` or `svn switch` commands, rather than having that output be suppressed.

**Comment by billsacks** [comment]
@bandre-ucar should we close this in favor of #49 (which seems to capture the thoughts here)?

**Comment by bandre-ucar** [comment]
Closed by GH-63
