### ISSUE TITLE
Enhancement request: mechanism to see what's currently checked out

### ISSUE THREAD

**Issue by billsacks** [ESMCI/manage_externals#48]
I'm opening this enhancement request on behalf of @cecilehannay , but I see her point, too.

It would be good to have a way to see what's currently checked out. This is similar to #14 , and if that were done, this one wouldn't be absolutely necessary. But it would still be helpful if the status command or some other command - or perhaps the status command with the -v option - showed the current branch/tag that is checked out.

The use case is: If you're not sure whether you updated all externals correctly (e.g., "Shoot, did I remember to run checkout_externals before I ran that case?"), it would be helpful to see at a glance what you have checked out.

**Comment by bandre-ucar** [comment]
Closed by GH-63
