### ISSUE TITLE
checkout_externals should have include/exclude options 

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/manage_externals#62]
Summary of Issue: checkout_externals currently wants to update all of the externals in the sandbox, but often I want to update only some of the components, or there is a particular component I do not want to update. I think that this can be easily handled with --include and --exclude options to checkout_externals
Expected behavior and actual behavior: only those externals in the include list (or not in the exclude list) would be updated.

**Comment by ekluzek** [comment]
The positional arguments take care of the include part of this request. There is a new issue under #140 to add the exclude part. As such I'm closing this.
