### ISSUE TITLE
When pointing to a git hash, sometimes says out-of-sync when really in-sync

### ISSUE THREAD

**Issue by billsacks** [ESMCI/manage_externals#68]
### Summary of Issue:

If you point to a git hash, sometimes `checkout_externals` says we're out-of-sync when really we're in-sync. This happens when the abbreviated hash printed by `git branch --verbose --verbose`, (e.g., `(HEAD detached at cade91dfe)`) has a different number of characters than the hash listed in the externals description file.

This is a problem if the full 40-character hash is listed in the externals description file, or if the number of characters used in the abbreviation in the externals description file differs from the number of characters printed by git.

Furthermore, running `checkout_externals` to bring things in sync does not resolve this problem: it continues to mark the given external as out-of-sync.

### Expected behavior and actual behavior:

Expected behavior: If we're detached at a hash, and we're at the same hash as the one listed in the externals description file, then checkout_externals should say we're in sync.

Actual behavior: see above.

### Steps to reproduce the problem (should include model description file(s) or link to publi c repository):

```
git clone -b cism2_1_46 git@github.com:ESCOMP/cism-wrapper.git
cd cism-wrapper
./manage_externals/checkout_externals
```

In the `cime` section of `Externals.cfg`, change the sha to point to the full 40-character sha: `cade91dfea97ca6ac4e2448173e6f5ad4a13b90f`.

Then run: `./manage_externals/checkout_externals -S -v`

### What is the changeset ID of the code, and the machine you are using:

659854797919defb70f5e376f9cdabadc103d0c4

Mac with `git version 2.14.1`

### have you modified the code? If so, it must be committed and available for testing:

No

### Screen output or log file showing the error message and context:

```
Checking status of externals: cism, source_cism, mosart, ctsm, fates, ptclm, cime,
s   ./cime
        clean sandbox, cade91dfe --> cade91dfea97ca6ac4e2448173e6f5ad4a13b90f
```

**Comment by billsacks** [comment]
@bandre-ucar I'm not sure how to fix this problem.

At first I thought we could put in place the rule that you should write out the full 40-character hash in the externals description file, and I tried:

```diff
diff --git a/manic/repository_git.py b/manic/repository_git.py
index d119879..f70b9ba 100644
--- a/manic/repository_git.py
+++ b/manic/repository_git.py
@@ -550,7 +550,7 @@ def _git_branch_vv():
         upstream tracking and hash.

         """
-        cmd = ['git', 'branch', '--verbose', '--verbose']
+        cmd = ['git', 'branch', '--verbose', '--verbose', '--no-abbrev']
         git_output = execute_subprocess(cmd, output_to_caller=True)
         return git_output
```

But that didn't help: it appears that the `--no-abbrev` flag changes the hash printed in one place, but not the place that matters:

```
* (HEAD detached at cade91dfe) cade91dfea97ca6ac4e2448173e6f5ad4a13b90f Merge pull request #2169 from billsacks/fix_pylint_error
```

So then I thought about changing the regex match used in `_current_ref_from_branch_command` to pick up the full hash in the above. But it looks like `RE_DETACHED` is used in some other contexts (e.g., detached at a tag), which I'd likely break if I did this in the way I was thinking.

Another option would be to keep the `_current_ref_from_branch_command` code as is (without bothering with `--no-abbrev`), but then add some logic in `compare_refs` that is more robust in this respect in terms of saying whether two hashes are identical. But I'm not sure the best way to do this.

@bandre-ucar do you have any ideas here?

**Comment by billsacks** [comment]
By the way: The reason this came up - and the reason I think this is worth solving - is because different git versions use different numbers of characters in the abbreviated hash. In the above case, git 2.14.1 abbreviates the hash as cade91dfe, whereas git 2.10.2 abbreviates it as cade91d. So if you write the externals description so that `checkout_externals` says you're in-sync on one machine, it will say you're out-of-sync on a different machine.

**Comment by billsacks** [comment]
I think I see a relatively easy solution (at least, it seems relatively easy at first glance, but I haven't tried implementing it yet): First, use `--no-abbrev`, as noted above. Then, in `_current_ref_from_branch_command` and the associated regex search using `RE_DETACHED`: Get two candidates for the "current ref": the one that we're currently using plus the full hash. Then, in `_check_sync_logic` and its internal `compare_refs`: treat us as being in sync if the expected ref matches any of a number of candidates for the current ref (in this case, we'll have two candidates).

I'm trying to think of unintended consequences of this change. The one behavior change I can see is: If the externals configuration lists a hash and we're actually on a tag or branch that is checked out at that hash, I think this change would lead us to remain on that tag or branch, rather than ending up in detached head state detached at that hash. In my mind, that is a positive or neutral side-effect of this change.

I can take a stab at implementing this.

**Comment by bandre-ucar** [comment]
I don't think --no-abbrev + complicated regexp for two hashes is the correct fix to this. The user can supply any arbitrary truncated hash, and what I understand of the proposed fix doesn't address this, only the full hash case. The bug is in compare refs expecting an exact match. It needs to be updated to handle the arbitrary length matching correctly. I think it's a fairly small update, ~6 lines + unit tests. I will prototype to test my fix today.

**Comment by billsacks** [comment]
> I don't think --no-abbrev + complicated regexp for two hashes is the correct fix to this. The user can supply any arbitrary truncated hash, and what I understand of the proposed fix doesn't address this, only the full hash case. The bug is in compare refs expecting an exact match. It needs to be updated to handle the arbitrary length matching correctly. I think it's a fairly small update, ~6 lines + unit tests. I will prototype to test my fix today.

You're right that my proposed fix doesn't address the arbitrary truncated hash case. I've come to feel that, if you list a hash in the externals description file, then you should list the full hash - but I left in place the original partial-hash matching for backwards compatibility.

I'm not sure I completely understand your suggestion, but: I thought very briefly about generalizing compare refs to allow partial matches, but it seems like that could open the door to its saying two refs match when they really don't (because, by chance, one is a substring of the other). Maybe ensuring that logic is only applied for hashes (not branch or tag names) would at least make it very unlikely to be a problem.... That said, if you have a robust solution to this, then I'm happy with that approach.

**Comment by bandre-ucar** [comment]
Closed by GH-84
