### ISSUE TITLE
error checking out optional rtm #4

### ISSUE THREAD

**Issue by bertinia** [ESMCI/manage_externals#7]
Error for RTM checkout returned when running command:

>./checkout_externals/checkout_externals.py -o

> Processing model description file : CESM.xml
> Processing model description file : CLM.xml
> Checking status of components: clm, fates, ptclm, mosart, ww3, cime, cice, pop, cism, rtm, cam, cime_config, 
> Enter passphrase for key '/home/aliceb/.ssh/id_rsa': 
> Enter passphrase for key '/home/aliceb/.ssh/id_rsa': 
> Checkout components: clm, fates, ptclm, mosart, ww3, cime, cice, pop, cism, rtm, 
> ERROR: CalledProcessError in "git checkout rtm1_0_62_cimeupdate_tags_n01"

Details from the checkout_externals.log file don't include the URL of the repo 
to help debug the problem:

> INFO : 2017-11-09 12:25:23 : In directory: /home/aliceb/checkout_testing/cesm-demo-externals/components/rtm
> execute_subprocess running command:
> INFO : 2017-11-09 12:25:23 : [u'git', u'fetch', u'--all', u'--tags']
> INFO : 2017-11-09 12:25:23 : git fetch --all --tags
> DEBUG : 2017-11-09 12:25:28 : Fetching origin
> DEBUG : 2017-11-09 12:25:28 : 
> INFO : 2017-11-09 12:25:28 : In directory: /home/aliceb/checkout_testing/cesm-demo-externals/components/rtm
> execute_subprocess running command:
> INFO : 2017-11-09 12:25:28 : [u'git', u'checkout', u'rtm1_0_62_cimeupdate_tags_n01']
> INFO : 2017-11-09 12:25:28 : git checkout rtm1_0_62_cimeupdate_tags_n01
> ERROR : 2017-11-09 12:25:28 : Command '[u'git', u'checkout', u'rtm1_0_62_cimeupdate_tags_n01']' returned non-zero exit status 1
> ERROR : 2017-11-09 12:25:28 : Returned : 1
> DEBUG : 2017-11-09 12:25:28 : error: pathspec 'rtm1_0_62_cimeupdate_tags_n01' did not match any file(s) known to git.
> DEBUG : 2017-11-09 12:25:28 : 
> ERROR : 2017-11-09 12:25:28 : CalledProcessError in "git checkout rtm1_0_62_cimeupdate_tags_n01"
> INFO : 2017-11-09 12:25:28 : 
> ERROR: CalledProcessError in "git checkout rtm1_0_62_cimeupdate_tags_n01"

**Comment by bertinia** [comment]
@bandre-ucar is adding more generic error checking with meaningful messages in the log.

**Comment by bandre-ucar** [comment]
I cleaned up the error handling from subprocess calls a bit in 2324d02ff.

In the specific case for this issue, the specified tag was not present in any of the remotes. Error handling to check for the existence of a tag was added in 300980136.

I think I've done everything I can related to this issue.
