### ISSUE TITLE
Bug in --status regex

### ISSUE THREAD

**Issue by billsacks** [ESMCI/manage_externals#71]
_From @jedwards4b on February 20, 2018 19:48_

### Expected behavior and actual behavior:I have a clm checkout that looks like 
```
git status
On branch pio2_cleanup
Your branch and 'mydev/pio2_cleanup' have diverged,
and have 62 and 2 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   src/main/ncdio_pio.F90.in

no changes added to commit (use "git add" and/or "git commit -a")
```
Current behavior is:
``` 
Processing externals description file : Externals.cfg
Processing externals description file : Externals_CLM.cfg
Processing externals description file : Externals_POP.cfg
Processing externals description file : Externals_CISM.cfg
Checking status of externals: clm, 
ERROR: DEV_ERROR: regex to detect tracking branch failed.
```
If I changes the RE_TRACKING to be     RE_TRACKING = re.compile(r'\[(.+)\]')
then I get what I think that I should expect:

```
Processing externals description file : Externals.cfg
Processing externals description file : Externals_CLM.cfg
Processing externals description file : Externals_POP.cfg
Processing externals description file : Externals_CISM.cfg
Checking status of externals: clm, fates, ptclm, mosart, ww3, cime, cice, pop, cvmix, marbl, cism, source_cism, rtm, cam, 
sM  ./cime
        modified sandbox, cesmdev/master: ahead 136 --> cime5.4.0-alpha.23
 M  ./components/cam
        modified sandbox, on cam1/trunk_tags/cam5_4_166/components/cam
s   ./components/cice
        clean sandbox, origin/master --> cice5_20180123
    ./components/cism
        clean sandbox, on cism2_1_46
    ./components/cism/glimmer-cism
        clean sandbox, on test_coupling_move_up_v2_n01
sM  ./components/clm
        modified sandbox, mydev/pio2_cleanup: ahead 62, behind 2 --> clm5.0.dev001
    ./components/clm/src/fates
        clean sandbox, on fates_s1.4.1_a3.0.0_rev3
s   ./components/clm/tools/PTCLM
        clean sandbox, PTCLM2_171216c --> PTCLM2_180214
    ./components/mosart
        clean sandbox, on mosart1_0_30
    ./components/pop
        clean sandbox, on pop2/trunk_tags/cesm_pop_2_1_20180205
    ./components/pop/externals/CVMix
        clean sandbox, on v0.72-conv_bugfix.002
    ./components/pop/externals/MARBL
        clean sandbox, on MARBL/trunk_tags/MARBL0_22_0
    ./components/rtm
        clean sandbox, on rtm1_0_65
    ./components/ww3
        clean sandbox, on ww3/trunk_tags/ww3_180115
```

### Screen output or log file showing the error message and context:

_Copied from original issue: ESCOMP/cesm#24_

**Comment by billsacks** [comment]
@jedwards4b - I agree this is a bug, but I don't think your suggested regex is right. I'd like @bandre-ucar 's confirmation here, but I think the purpose of the `RE_TRACKING` regex is to pick up just the name of the remote branch that we're tracking. Your regex results in its picking up the following for this name: `mydev/pio2_cleanup: ahead 62, behind 2`, whereas it should just pick up `mydev/pio2_cleanup`.

It looks like the problem with the original regex is that it assumes that the ']' character comes right after the branch name, which isn't true if you are behind or ahead of the remote branch. So I think the right fix is to add `.*` before the ']'.

Can you try these diffs and see if they work for you?:

```diff
diff --git a/manic/repository_git.py b/manic/repository_git.py
index d119879..d8cd75a 100644
--- a/manic/repository_git.py
+++ b/manic/repository_git.py
@@ -44,7 +44,7 @@ class GitRepository(Repository):

     # match tracking reference info, return XYZ from [XYZ]
     # e.g. [origin/master]
-    RE_TRACKING = re.compile(r'\[([\w\-./]+)\]')
+    RE_TRACKING = re.compile(r'\[([\w\-./]+).*\]')

     def __init__(self, component_name, repo):
         """
```

**Comment by jedwards4b** [comment]
Sure that would work.

**Comment by bandre-ucar** [comment]
The original proposed fix is too loose and matches `cesmdev/master: ahead 136`, which will fail when it tries to checkout the resulting ref. I think @billsacks fix is better, but may still be too loose. I'd be more comfortable with something like `r'\[([\w\-./]+):?.*\]'`.

Also an update to the unit tests to ensure this is maintained going forward.

I can fix this today if no one else wants to add the unit tests.

**Comment by billsacks** [comment]
@bandre-ucar Does adding `:?` to the regex actually make the match any more specific? Since it's an optional match, I'd think that would match exactly the same things that my proposal matches. That said, it certainly won't hurt anything, so I'm willing to trust you if you can see a reason why it's better.

**Comment by billsacks** [comment]
> I can fix this today if no one else wants to add the unit tests.

That would be great - I'm way behind on other things. Thanks.
