### ISSUE TITLE
End up in incorrect state when an external has changed its own externals file

### ISSUE THREAD

**Issue by billsacks** [ESMCI/manage_externals#72]
### Summary of Issue:

When rerunning `checkout_externals`, if the top-level externals configuration has changed to update one of the externals, and the new version of that external itself has a changed sub-externals file (i.e., one referenced recursively), we end up in the wrong state: We end up with the old versions of the sub-externals rather than the updated versions.

### Expected behavior and actual behavior:

Expected: If an external is updated, then a single run of `checkout_externals` should give us that updated external as well as the correct versions of all updated sub-externals.

Actual: In the first run of `checkout_externals`, the sub-externals aren't updated. It takes a second run to update them.

### Steps to reproduce the problem (should include model description file(s) or link to publi c repository):

```
git clone git@github.com:ESCOMP/cesm.git
cd cesm
git checkout cesm2_0_beta09
./manage_externals/checkout_externals
sed -i '' -e 's/clm4_5_18_r274/clm5.0.dev001/' Externals.cfg
./manage_externals/checkout_externals -v
```

Then, notice that ptclm and fates are not up-to-date: `./manage_externals/checkout_externals -S -v`

gives (among other things):

```
s   ./components/clm/src/fates
        clean sandbox, fates_s1.4.1_a3.0.0_rev2 --> fates_s1.4.1_a3.0.0_rev3
s   ./components/clm/tools/PTCLM
        clean sandbox, PTCLM2_171216c --> PTCLM2_180214
```

Running checkout_externals a second time brings things up to date

### What is the changeset ID of the code, and the machine you are using:

v0.8.0 on my mac

### have you modified the code? If so, it must be committed and available for testing:

no

### Screen output or log file showing the error message and context:

See above

**Comment by billsacks** [comment]
@bandre-ucar this seems important to fix.

When doing an initial checkout, `checkout_externals` is able to do the "correct" ordering: first getting each external, then parsing the sub-externals configuration files and getting the proper versions of each sub-external. So I assume it's possible to change the behavior when rerunning `checkout_externals` to work in the same order, but I don't know how hard that would be.

**Comment by bandre-ucar** [comment]
The problem is that after an external is updated, the objects representing it's sub-externals are potentially stale and out of sync with the description file. I have a branch with the fix, but I need to add a test.
