### ISSUE TITLE
Request for support of multiple optional groups 

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/manage_externals#80]
Instead of the required field being a bool , what if it were a list of one or more groups so 
for example cvmix would have:

required = pop, mom

while fms might have
required = mom, camfv3

then the -o argument to checkout_externals would expect a list of one or more optional components.

**Comment by gold2718** [comment]
I am not sure I like this. For one thing, there is no such thing as camfv3. FV3 is a dycore that is selected via the `--res` argument to `create_newcase` and I do not think the user should have to keep track of which optional repositories are going to be required for the case they have not yet created. I would prefer a command line option allowing me the ability to specify an external to load. Some ideas:
```
--optional=FV3
--only=FV3,FMS
```
Then, I could check and load these externals in `buildcpp` like I am currently doing in my pause/resume work. Something like:
```
    sys.path.insert(0, os.path.join(srcroot, "manage_externals"))
    import manic.checkout
    fms_path = os.path.join(srcroot, "components", "cam", "src", "dynamics", "fv3")
    if not os.path.isdir(fms_path):
        cam_cfg = os.path.join(srcroot, "components", "cam", "Externals_CAM.cfg")
        cwd = os.getcwd()
        os.chdir(os.path.join(srcroot, "components", "cam"))
        cargs = [ "--externals", cam_cfg, "--no-logging", "--only=FV3" ]
        args = manic.checkout.commandline_arguments(args=cargs)
        try:
            ret_status, _ = manic.checkout.main(args)
...
```

**Comment by jedwards4b** [comment]
camfv3 was only a hypothetical.   I don't have any objection to your idea but don't know if I understand how it would work for a top level cesm checkout - remember the FMS is optionally checked out at the top level so somehow FV3 in Externals_CAM.cfg needs to indicate that it's dependent on FMS at the cesm level - how does that work?

**Comment by gold2718** [comment]
Actually, belay that request. A more straightforward approach is to simply create a file:
`<root>/components/cam/src/dynamics/fv3/Externals_FV3.cfg`
This file would contain the external repo for FV3 which would be pulled into the `source` subdirectory while the fv3 directory would also contain the interface code.
Then, I can use `checkout_externals` exactly as I use it today so I now claim that no changes are necessary to `manage_externals` (at least for this issue).
This leaves loading of optional repos in the hands of the components which should know what they need for any particular case.

**Comment by gold2718** [comment]
For FMS, the most straightforward method I can think of is to add an `Externals_FMS.cfg` file to the CESM root. Then, any component (e.g., MOM, CAM running the FV3 dycore) could make sure this external is loaded during `case.setup` and load it if necessary.

**Comment by jedwards4b** [comment]
I'm concerned that we could end up with a multitude of Externals files in this case - I can already think of two - couldn't the component just refer back to an optional entry in the single Externals.cfg file at the top level?

**Comment by gold2718** [comment]
Yes, we could have FMS inside the standard Externals.cfg file if my first suggestion is implemented. I still think the component should be in charge of making sure an optional component is loaded although we can provide a case interface in CIME to simplify the code that each component needs to call.

**Comment by jedwards4b** [comment]
What if the ```/components/cam/src/dynamics/fv3/Externals_FV3.cfg``` had something like
```
[FMS]
redirect = $SRCROOT/Externals.cfg
```
To tell checkout externals that it needs FMS but that the config is elsewhere?

**Comment by gold2718** [comment]
It would not hurt but also does not seem necessary since I already have to know where the `srcroot` directory is.
I feel this is more a CIME case management issue than a manage_externals issue, however, we could have checkout_externals walk the externals 'tree' starting from `srcroot` and load whatever external is passed on the command line. Then, `./manage_externals/checkout_externals FMS` would find FMS in Externals.cfg and load it while `./manage_externals/checkout_externals FV3` would find FV3 in Externals_CAM.cfg and load it from there. Might need to include the calling component so that only that component's Externals file is searched to avoid duplicates.

**Comment by jedwards4b** [comment]
It is a manage_externals issue because whatever we decide we will need to implement in checkout_externals - I don't see any good way to do it based on the features currently available.

**Comment by gold2718** [comment]
Agreed (assuming you are labeling the proliferation of files such as Externals_FMS.cfg as a 'not good' way). I just think we should design how we want CIME-based cases to respond to optional components first and then ask manage_externals for any missing functionality.

**Comment by jedwards4b** [comment]
Isn't that what we are doing?

**Comment by gold2718** [comment]
Yes but maybe in the wrong repo's issue board (I don't really know).
So how about a new CIME interface like:
```
case.check_optional_component(<optional_compname>, <calling_component>)
```
which would load `<optional_compname>` if necessary and throw a friendly error if it cannot be loaded ("ERROR: case foo cannot be build because component <optional_compname> is not available).

**Comment by jedwards4b** [comment]
I think that you are approaching backward - we need the low level functionality first the high level will follow.

**Comment by gold2718** [comment]
How do you know what low-level function we need if we do not know our need? To me, the whole issue is that CIME components need to be able to build in the presence of optional components which may or may not already be loaded in the sandbox. We also want to avoid the proliferation of externals[_comp].cfg files or no new low-level functionality is needed. Therefore, it is really top-down design issues that will drive the final form of the lower-level request.
