### ISSUE TITLE
Prevent result of --status from being an error code

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/manage_externals#89]
### Summary of Issue:

manage_externals will return an error code even for "--status" if there is a missing Externals file or some other problem running manage_externals.

### Expected behavior and actual behavior:

Error code is returned for "--status" if an Externals file is missing. I expect --status to not return an error code. 

### Steps to reproduce the problem (should include model description file(s) or link to publi c repository):

  1179	23:15	cd ctsm/
  1180	23:15	rm Externals.cfg
  1181	23:15	./manage_externals/checkout_externals --status
  1182	23:15	echo $?

### What is the changeset ID of the code, and the machine you are using:

manicv1.0.2
81ccf92e8c4da272121fcc96902021be9e7a7b1f

cheyenne

### have you modified the code? If so, it must be committed and available for testing:

no

### Screen output or log file showing the error message and context:

```
cheyenne4 erik/ctsm> ./manage_externals/checkout_externals --status
Processing externals description file : Externals.cfg
Processing externals description file : Externals_CISM.cfg

ERROR: External externals description file "Externals_CLM.cfg" does not exist! In directory: /glade/p/work/erik/ctsm
cheyenne4 erik/ctsm> echo $?
1
```

**Comment by ekluzek** [comment]
I can see an argument that --status should return an error for cases when the externals are screwed up, or as in this example missing. But, it can also be argued that "--status" should NEVER return an error code, or at least only for maybe the most catastrophic cases. I'd like the philosophy of one or other to be picked, or defined.

**Comment by billsacks** [comment]
@ekluzek I disagree. I feel it's important that we return an error code if something is really messed up with the externals file, thus indicating that we were not able to successfully determine a status.

If we made the change you're suggesting, then this would force our hand in https://github.com/ESMCI/cime/issues/2430 -- we wouldn't be able to error out if there's a problem determining status, even if we wanted to.

**Comment by ekluzek** [comment]
We've decided this is a WONTFIX, since it's legit for manage_externals to abort on an actual legitimate error. So we are leaving the current behavior in place.
