### ISSUE TITLE
ssh vs. https in checkout 

### ISSUE THREAD

**Issue by bertinia** [ESMCI/manage_externals#9]
This issue needs to be documented for developers checking out private repos;

On hobart, I'm getting this error:

> ./checkout_externals/checkout_externals.py --model CESM.cfg
> Processing model description file : CESM.cfg
> Checking status of components: clm, mosart, ww3, cime, cice, pop, cism, rtm, cam, cime_config, 
> The authenticity of host 'github.com (192.30.253.113)' can't be established.
> RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
> Are you sure you want to continue connecting (yes/no)? yes
> Checkout components: clm, 
> ERROR: CalledProcessError in "git clone git@github.com:NCAR/clm-demo-externals.git clm"

Similar error when specifying --model CESM.json:

> ./checkout_externals/checkout_externals.py --model CESM.json
> Processing model description file : CESM.json
> Checking status of components: clm, mosart, cime, ww3, cice, pop, cism, rtm, cam, cime_config,
> Checkout components: clm,
> ERROR: CalledProcessError in "git clone git@github.com:NCAR/clm-demo-externals.git clm"

Is there a reason to use the ssh clone command as opposed to the https?
**Yes, for private repos, access via ssh is required.** 

When reviewing the README_FIRST, it points to:

> https://help.github.com/articles/connecting-to-github-with-ssh/

and I also tried running the tool:

> http://tools.cgd.ucar.edu/make_user_ssh_keys/index.html

on hobart using:

> ./mk_user_ssh_keys.sh -t github.com -u bertinia -v

But I'm getting permission denied errors from the target cause I think the only
way to add an ssh key on github is via the web interface settings in my profile.

I added the hobart ssh key to my github profile via the web settings and was able to
get the download to work correctly.

We will need more explanation of how to setup the ssh keys in the README_FIRST
if we use the ssh clone link. 

**According to @goldy2718, we will use https protocol for public released versions of the model. 
Developers will still need to add ssh keys to their profiles when downloading private repos.**

**Comment by bertinia** [comment]
@bertinia will add a short section to the https://github.com/ESCOMP/cesm/blob/master/README.rst
with some explanation re: ssh vs. https. CESM.cfg will default to use https but users modifying their sandbox via a custom CESM.cfg file in order to access a private repo may chose to use ssh and ssh-keys for external management.

**Comment by bandre-ucar** [comment]
This is not really an issue for manage_externals, but how CESM is creating externals description files and documenting their workflows.

Moving discussion to: https://github.com/ESCOMP/cesm/issues/12
