### ISSUE TITLE
Should we fetch from git repo before showing status?

### ISSUE THREAD

**Issue by billsacks** [ESMCI/manage_externals#94]
### Summary of Issue:

At least for branches (and possibly for tags that have been changed - though ideally that should never happen): If there have been changes on the remote that have not yet been fetched, then `checkout_externals -S` can show you as being in-sync when really you're out of sync.

It seems like checkout_externals should fetch from the specified remote before showing you the status.

### Expected behavior and actual behavior:

Expected behavior: If your config file points to a branch and your local version of the branch is behind the remote's, it should say you're out-of-sync, even if your local version matches the last-fetched version of the remote. i.e., it should do a fetch before determining if you're in sync.

Actual behavior: Status determines that you're in-sync based on the last time you fetched, not based on what's currently on the remote.

### Steps to reproduce the problem (should include model description file(s) or link to publi c repository):

1. `git clone git@github.com:ESCOMP/cesm.git` and run `checkout_externals`

2. Make a new branch in cime, add a commit to the branch, then push it to a remote

3. Change `Externals.cfg` to point to your new branch

4. From another clone of cime: fetch the branch, make a commit, then push it.

5. Back in your cesm checkout: Run `checkout_externals -S`. It will incorrectly show that you're in sync.

6. From `/path/to/cesm_checkout/cime`: Fetch from the remote. Then rerun `checkout_externals -S`. It will now show (correctly) that you're out-of-sync.

### What is the changeset ID of the code, and the machine you are using:

manic-v1.1.1

### have you modified the code? If so, it must be committed and available for testing:

No

### Screen output or log file showing the error message and context:

n/a

**Comment by billsacks** [comment]
As I think about this more, I'm not sure if this is a good idea. Currently, I _think_ `checkout_externals -S` (1) doesn't change anything about your local repositories, (2) therefore doesn't require write permission in those directories (e.g., see the cime issue referenced by #95 ), and (3) doesn't require an internet connection for git repos. All of those seem like good things.

So maybe we should just keep the current behavior and try to document it well.

What do others think?

**Comment by ekluzek** [comment]
@billsacks I agree with your latest statement. Status shouldn't change anything, especially something that requires write permission, which it sounds like a fetch does. I also agree with you that status shouldn't require a network connection.

I think the non status mode does an equivalent of a fetch though right? Or maybe it does a full up fetch? That does make sense to me.

**Comment by billsacks** [comment]
Thanks for your thoughts @ekluzek . Yes, running without `--status` does a fetch.

I'll close this as a wontfix.
