### ISSUE TITLE
Should not write to log file when running status command

### ISSUE THREAD

**Issue by billsacks** [ESMCI/manage_externals#95]
The fact that checkout_externals writes to a log file, even when running --status, bit me again: https://github.com/ESMCI/cime/issues/2443 . I had originally opened #47 , and this was resolved by Ben's adding a flag to avoid logging, but I really feel that logging should be off by default when running the `--status` command.

What do others think?

**Comment by ekluzek** [comment]
@billsacks I agree, it would be good for status to automatically flag logging off, unless you explicitly ask for it.
