### ISSUE TITLE
Hangs and times out during checkout of cam.

### ISSUE THREAD

**Issue by fischer-ncar** [ESMCI/manage_externals#97]
### Expected behavior and actual behavior:  

Exected behavior:
   Checkout cam an not hang.

Actual behavior:
  Hangs and times out at the cam checkout step.

### Steps to reproduce the problem (should include model description file(s) or link to publi c repository):
Use any release, manic-v1.0.2 or newer, or use ESMCI/manage_externals master.
Follow normal steps to run checkout on cheyenne or hobart.

manic-v1.0.1 runs just fine.

### have you modified the code? If so, it must be committed and available for testing:
Nope

### Screen output or log file showing the error message and context:
Checking out externals: clm, mosart, ww3, cime, cice, pop, cism, rtm, cam, 

ERROR: subprocess call to  'svn' has exceeded timeout limit of 300 seconds.
 Timout errors typically occur when svn or git requires
authentication to access a private repository. On some systems, svn
and git requests for authentication information will not be displayed
to the user.  In this case, the program will appear to hang and
generate a timeout error. Ensure you can run svn and git manually and
access all repositories without entering your authentication
information.

**Comment by billsacks** [comment]
That happened to me recently, too, but I had chalked it up to user error (I might have closed my laptop partway through checkout). Would this be as simple as increasing `_TIMEOUT_SEC` in utils.py?

**Comment by fischer-ncar** [comment]
A manual checkout of cam takes around 30 seconds.  So the 300 second timeout should be plenty.

**Comment by billsacks** [comment]
It just took about 90 sec for me (over my home's wifi). I know sometimes the svn server can be sluggish. Is there a downside to increasing this timeout?

Actually, let me back up: Do you know what actually happened in your case? Did it hang without doing anything, or did it get cam partially but not fully checked out? If the latter, that suggests to me increasing the timeout.

**Comment by fischer-ncar** [comment]
@jedwards4b did a verbose checkout_externals, and cam didn't even start downloading.

**Comment by billsacks** [comment]
Is this related to https://github.com/ESMCI/manage_externals/issues/79?

**Comment by fischer-ncar** [comment]
The subversion password isn't missing in this case.  I think it's related in the fact that Ben might have added 
more error checking that's causing the hang.

**Comment by jedwards4b** [comment]
I'm having trouble figuring this out.   It takes around 20-30s to checkout cam from the command line using exactly the same arguments I'm passing to pythons subprocess but the subprocess timesout 
with the repo only partially checkedout after 10 minutes.

**Comment by billsacks** [comment]
I see that the checkout command does not use `--quiet`:

https://github.com/ESMCI/manage_externals/blob/b2f3ae8e251371bdb451d566dfa124e0c826a4b5/manic/repository_svn.py#L263

I wonder if it takes a long time due to the capturing of all of the output from the `svn checkout` command. Does it get significantly faster if you add `--quiet` to the above command?

**Comment by jedwards4b** [comment]
Yes that fixed it.   Pushed directly to master.   Thanks - I think that the current behavior of always writing a manage_externals.log could also be a problem, I think that --no-logging should be the default.

**Comment by billsacks** [comment]
> Thanks - I think that the current behavior of always writing a manage_externals.log could also be a problem, I think that --no-logging should be the default.

I agree. Ben wanted logging on by default, but I don't find much value in it. (To be honest, I rarely look in the log file... maybe if I looked there, I'd find more value... but I'm fine with --no-logging being the default.)

**Comment by gold2718** [comment]
I second (third?) the call to have --no-logging be the default.
